### ISSUE TITLE
Changes my HTML tags and rewrites them

### ISSUE THREAD

**Issue by kgoedecke** [macedigital/gulp-sri-hash#11]
For some weird reason this plugin rewrites my html file and moves closing tags of `</html>` and `</body>` around. I'm using it with PHP files and have the `</html>` and `</body>` in a different file than the opening tag. Yet the plugin shouldn't be bother.

**Comment by macedigital** [comment]
@kgoedecke Yes, this plugin updates the HTML markup in a way that missing closing tags are added. The library responsible here is [cheerio](https://github.com/cheeriojs/cheerio). It basically converts text based HTML into a DOM-tree and then saves/creates a HTML string back from it.

Although I'm investigating alternative libraries, this behavior is intended and unlikely to change in the near future. All input files are supposed to be valid HTML files. At the moment, PHP pre- or post-processing is not supported (nor is any other template library for that matter).

I hope this clears things up a bit. Maybe you can post an example of how your files look like. There might be a different solution. In the end you could also calculate file-content checksums in PHP.

**Comment by kgoedecke** [comment]
thanks @macedigital for getting back to me.

I already figured that cheerio is actually doing that. I also looked into cheerio if theres a way to disable this kind of feature, but it doesnt seem like it. My current project is based on WordPress and the nature of the WordPress structure dictates that the header, footer and actual content files are separated.

**Comment by macedigital** [comment]
You're welcome @kgoedecke.

In your case, you could check if https://wordpress.org/plugins/wp-sri/ works out for you, or add a function that calculates the hash, like so:

```php
<?php

function getSha256SriHash($filepath) {
    $algo = 'sha256';
    $data = file_get_contents($filepath);
    $hash = base64_encode(hash($algo, $data));

    return join([$algo, $hash], '-');
}
```

Sorry for the inconvenience.
