### ISSUE TITLE
Gulp dependency

### ISSUE THREAD

**Issue by XhmikosR** [macedigital/gulp-sri-hash#14]
Hi, @macedigital. Why is gulp a dependency? Shouldn't it be a peerDependency?

**Comment by XhmikosR** [comment]
If my assumption is right, can you release a patch version (before 2.0.0) which removes the gulp dependency?

**Comment by XhmikosR** [comment]
Actually, scratch that. I made a PR.

**Comment by macedigital** [comment]
@XhmikosR Sorry, I'm in full-on holiday mode until the end of the month.

I'll do a 1.x release soon-ish, which moves the gulp to devDependencies.

**Comment by XhmikosR** [comment]
Thanks! I should have caught this earlier but better late than never :)

It was the security advisories that led me to check which of my packages were requiring the old gulp version.

**Comment by macedigital** [comment]
Your welcome! And ah, yes, those nice `npm audit` messages ...

**Comment by XhmikosR** [comment]
BTW, you can release 2.x directly and not 1.x for all I care :) Node.js 4 is old anyway so let those suffer :P

**Comment by macedigital** [comment]
@XhmikosR Well, you can pick your poison with either v2.0.0 or v1.6.0 now :see_no_evil:

**Comment by XhmikosR** [comment]
Hehe, awesome, thanks!
