### ISSUE TITLE
Paths for scripts should use `path.posix`

### ISSUE THREAD

**Issue by XhmikosR** [macedigital/gulp-sri-hash#16]
I don't know if Windows paths in URLs are allowed, but IMO it's a standard practice to use unix paths in scripts.

**Comment by macedigital** [comment]
@XhmikosR  I'm afraid I don't follow. Can you elaborate a bit more what you mean (or provide an example/line in the code)?

**Comment by XhmikosR** [comment]
All `path.join`, `path.sep` etc methods are OS specific. But I don't think it makes sense to have Windows `\` in those paths, don't you agree?

**Comment by macedigital** [comment]
Ah, I think I understand now. I'm assuming you're referring to this https://github.com/macedigital/gulp-sri-hash/blob/0e0ae42bb2201533ab64d972797b2bbb4aef5ee4/index.js#L32.

Contents of referenced asset **files have to be on the local filesystem** (loading remote resources is not supported). So, path resolution on Windows _might_ indeed fail if the asset path looks like this `/some/path`, which would be resolved to `\\\\some\\path`. (POSIX compliant OSes aren't affected).

Path resolver on Windows:

![path-on-win](https://user-images.githubusercontent.com/248495/41725181-802da8c6-756f-11e8-9605-6cd849f077a4.gif)

**Comment by XhmikosR** [comment]
Ah, OK. We'll see if anything breaks anyway :)

**Comment by macedigital** [comment]
Haha, well I guess I could add a test case :smile:
