### ISSUE TITLE
`doctype` becomes uppercase after using gulp-sri-hash

### ISSUE THREAD

**Issue by XhmikosR** [macedigital/gulp-sri-hash#21]
So, this must be due to the new cheerio version.

@macedigital I wonder, is it possible to work around this? Maybe limit what cheerio changes in the HTML files?

**Comment by XhmikosR** [comment]
@macedigital; do you have any workaround about this?

**Comment by macedigital** [comment]
@XhmikosR Yes, looks like the new parser in cheerio does that (see discussion regarding https://github.com/cheeriojs/cheerio/pull/985, etc.). 

I just released v1.7.0, which has all changes for the gulp-sri-hash 2.0 release, but still uses cherio@0.22 as a dependency.

Regarding workaround: The old behavior can be achieved by explicitly configuring cheerio with `cheerio.load(file.contents, { xmlMode: true })`;

Modifying parser configuration from the gulp-plugin isn't implemented yet, so better stick to v1.x for the moment.

**Comment by XhmikosR** [comment]
Thanks, @macedigital!
