### ISSUE TITLE
Wrong sha512 calculation(?)

### ISSUE THREAD

**Issue by ivostoykov** [macedigital/gulp-sri-hash#50]
Hello there,
I've faced a problem using sriHash - I get a wrong result and, unfortunately, can't find the reason.
here is the gulpfile.js
```
const gulp = require('gulp');
const uglify = require('gulp-uglify');
// const cssnano = require('gulp-cssnano');
const rename = require('gulp-rename');
const sriHash = require('gulp-sri-hash');
const gulpIf = require('gulp-if');
const path = require('path');

function isJavaScript(file) {
    return path.extname(file.path) === '.js';
}

function isCSS(file) {
    return path.extname(file.path) === '.css';
}

function isHTML(file) {
    return path.extname(file.path) === '.html';
}

function minifyFiles() {
    const root = "/home/";
    return gulp.src([`${root}/test.js`, `${root}/*.css`], { base: root })
        .pipe(gulpIf(isJavaScript, uglify()))
        .pipe(gulpIf(isJavaScript, rename({ suffix: '.min' })))
        .pipe(gulpIf(isCSS, rename({ suffix: '.min' })))
        .pipe(gulp.dest(root));
}

function addSriHash() {
    const root = "/home/";
    return gulp.src([`${root}/test.min.js`, `${root}/*.min.css`, `${root}/test.html`], { base: root })
        .pipe(gulpIf(isHTML, sriHash({
            algo: 'sha512',        // Use strong hashing
            relative: false,       // Assets reside relative to HTML file
            selector: 'script[src],link[href]'
        })))
        .pipe(gulp.dest(root));
}

exports.watch = watch;
exports.sri = sri;
exports.minifyAndSri = gulp.series(minifyFiles, addSriHash);
exports.default = gulp.series(minifyFiles, addSriHash, watch);
// gulp.task('default', gulp.series('i', 'sri', 'watch'));
```
here is the HTML with the integrity updated:
```
<!DOCTYPE html><html lang="en"><head>
    <script src="/test.min.js" integrity="sha512-uklnmezB++Y6dEuG96QwvAHLoaK5IyI/8OE8v9OtkZN6zInKmXBLDUN+ph9kZfBRyshMS/AFaK4xdtn97UWfLA==" crossorigin="anonymous"></script>
</head><body></body></html>
```
here is the browser rejected the script:
`test.html:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://beatrootskin.com/test.min.js' with computed SHA-512 integrity 'j1+y05RrFJyuau4lA5OlWLqR57jVEOPO/55Q8YyLsWFW89nrhgUDBsNLLLZcnblVmpOrKLOjABQhzps8y6dCbg=='. The resource has been blocked.`

here is the manual calculation:
```
$ openssl dgst -sha512 -binary test.min.js | openssl base64 -A
j1+y05RrFJyuau4lA5OlWLqR57jVEOPO/55Q8YyLsWFW89nrhgUDBsNLLLZcnblVmpOrKLOjABQhzps8y6dCbg==
```
here is the GtkHash calculation:
`j1+y05RrFJyuau4lA5OlWLqR57jVEOPO/55Q8YyLsWFW89nrhgUDBsNLLLZcnblVmpOrKLOjABQhzps8y6dCbg==`

Sorry for the long post, but I'll gratefully appreciate your help. 
Thank you
Ivo

PS: Here is the minified script:

`document.addEventListener("DOMContentLoaded",function(){console.log(document.getElementsByTagName("body").length)});`

**Comment by ivostoykov** [comment]
Well, after some investigations, I found the following:
- Executing minifyAndSri task does not calculate the hash correctly. I guess that processes overlap, and calculation is applied before the previous task (minification) is completed.
- Once separated, and if the addSriHash task is executed alone - it works fine, and the result is correct.

I'm going to close this issue because it looks like there is nothing wrong with the library. The problem is in my setup and configuration. But I'm still a bit muddled up and any comments will be appreciated.

**Comment by macedigital** [comment]
Hi @ivostoykov, sorry for the delay. Luckily you found a solution on your own. 

I spend some time to reproduce the exact behavior you're describing, but couldn't. From what I noticed, you're potentially overwriting the source files, and I would instead recommend that the output of gulp should be a new directory.

To give you an idea what I mean, I altered the `gulpfile.js` you provided, and modified it so it reads files from a `src` folder, and puts its output to a folder called `dest`.

```js
// gulpfile.js
const gulp = require('gulp');
const uglify = require('gulp-uglify');
const rename = require('gulp-rename');
const sriHash = require('gulp-sri-hash');
const gulpIf = require('gulp-if');
const path = require('path');

const hasSuffix = (file, suffix) => path.extname(file.path) === suffix;
const isJavaScript = file => hasSuffix(file, '.js');
const isCSS = file => hasSuffix(file, '.css');

const SRC_ROOT = "./src/";
const DST_ROOT = "./dest/";
const SOURCES = [`${SRC_ROOT}/*.js`, `${SRC_ROOT}/*.css`, `${SRC_ROOT}/*.html`];

const minifyFiles = () => gulp.src(SOURCES)
    .pipe(gulpIf(isJavaScript, uglify()))
    .pipe(gulpIf(isJavaScript, rename({ suffix: '.min' })))
    .pipe(gulpIf(isCSS, rename({ suffix: '.min' })))
    .pipe(gulp.dest(DST_ROOT));

const addSriHash = () => gulp.src([`${DST_ROOT}/*.html`])
    .pipe(sriHash({
        algo: 'sha512'
    }))
    .pipe(gulp.dest(DST_ROOT));

gulp.task("default", gulp.series(minifyFiles, addSriHash));
```

After running `gulp`, the folder structure will look like this (where the contents of `dest` folder is the minified and content-hashed output, while `src` will remain unmodified.

```
dest
├── test.html
├── test.min.css
└── test.min.js
gulpfile.js
src
├── test.css
├── test.html
└── test.js
```

**Comment by ivostoykov** [comment]
Hi @macedigital,

Thank you for your reply, and I apologise for the trouble caused by my issue.

The problem stemmed from the processes of creating the file and hash calculations overlapping, with the calculations commencing before the OS had released the file from writing. Thus, it was evident that the write process completion, subsequent file alterations, and the calculated hash would not align.

I should have identified this issue sooner. Regrettably, it consumed an excessive amount of time, necessitating a workaround. Once rectified, however, everything functioned (and continues to function) smoothly.

Thank you,
Ivo
