### ISSUE TITLE
Ignore cache busting hash in URL

### ISSUE THREAD

**Issue by riklewis** [macedigital/gulp-sri-hash#7]
At the moment, if I have a process which adds a cache busting hash at the end of the URL, this plugin no longer works and I get an error such as...

> Error: ENOENT: no such file or directory, open 'C:\Users\projectpath\build\css\style.css?cbh=5da92178ce374635e14b17a2e0038469'

I've had to move my "gulp-hash-src" task to after this one, which is fine, but it would be better if it worked either way.

In short, perhaps when loading .js and .css files locally, you could ignore the query string ("?" onwards).

Cheers, Rik

**Comment by macedigital** [comment]
Hi Rik, thanks for your report.

With the latest commit, querystrings are now ignored when resolving file paths. That should fix the issue. 

I'll make a new release tomorrow.

**Comment by riklewis** [comment]
Great, thanks!

**Comment by macedigital** [comment]
@riklewis v1.4.0 is released.
